### ISSUE TITLE
Instructor Feedback - Week 4 - Hibernate

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [sasha802/choreography_builder#2]
Nice job implementing hibernate directly in your project!

1. ${filepath} - It looks like perhaps a proper value wasn't supplied in log 4 j for file path, as this is showing up in github as a file/directory?
2. Some formatting in the time log appears to be off. Example: 09/04/2018 has the hours on the following line.
3. Before you build too many more Daos, take a good look at the generic dao. You should be able to refactor to remove any specific daos and just use the generic for your db access.

**Comment by sasha802** [comment]
Thank you for your feedback I did fix the issues.
