### ISSUE TITLE
Instructor Feedback - Week 5 - Hibernate One-to-Many

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [sasha802/choreography_builder#3]
Nice job implementing a one-to-many in your project and Lombok! It looks like you have a good handle on Hibernate.

- [x] With regard to issues raised here, you can update the -[ ] when complete with -[x] and when all items are addressed, close the issue.
- [x] What do you think about adding one or more methods to the generic dao to handle situations like https://github.com/sasha802/choreography_builder/blob/a1ed55e3b99b85d3dc32ebb5edf0a666f5f82ce0/src/main/java/dance/builder/persistence/StepDAO.java#L18.   Could a generic getPropertyLike or getPropertyEqual method accept a collection of properties and values?
- [x] Could you use the .equals method on CustomStep to compare all values rather than just https://github.com/sasha802/choreography_builder/blob/a1ed55e3b99b85d3dc32ebb5edf0a666f5f82ce0/src/test/java/dance/builder/persistence/CustomStepsDAOTest.java#L53
- [x] What percent code coverage do you currently have in the persistence package?

**Comment by sasha802** [comment]
I fixed the first and 3rd issues

**Comment by sasha802** [comment]
Hello Paula, 
I tried to make getPropertyEgual to support my getStepByDance.
I think is the best way to go is to abstracted my getStepByDance to get more flexibility and except two property. in my situation I might reset it for my customStep DAO. 

It just makes more sense to not abstracted it completely.
Maybe I just missing something in my understanding. I just have more clarity to have it separately from getPropertyEqual.

**Comment by pawaitemadisoncollege** [comment]
Can you point me to the code where you attempted the change? Is it in a branch or??

**Comment by sasha802** [comment]
I was changing my StepDAO.
It is in the same location 
GetStepByDance method

**Comment by pawaitemadisoncollege** [comment]
This may help: https://stackoverflow.com/questions/11138118/really-dynamic-jpa-criteriabuilder

**Comment by sasha802** [comment]
Thank you for sharing the example. 
Here is what I've got.

**Comment by sasha802** [comment]
public List<T> getByMultiplePropertiesTopClause(Map<String, Map<String, String>> entities, int limit) {

        Session session = getSession();

        CriteriaBuilder builder = session.getCriteriaBuilder();
        CriteriaQuery query = builder.createQuery(type);

        Root<T> root = query.from(type);

        List<Predicate> predicates = new ArrayList<>();


        for (Map.Entry<String, Map<String, String>> firstEntry : entities.entrySet()) {

            String entity = firstEntry.getKey();
            Map<String, String> properties = firstEntry.getValue();

            for (Map.Entry<String, String> secondEntry : properties.entrySet()) {

                if (entity.isEmpty()) {

                    predicates.add(builder.equal(root.get(secondEntry.getKey()), secondEntry.getValue()));
                    break;

                }

                predicates.add(builder.equal(root.get(entity).get(secondEntry.getKey()), secondEntry.getValue()));

            }

        }


        query.select(root).where(predicates.toArray(new Predicate[]{}));

        List<T> result = session.createQuery(query).setMaxResults(limit).getResultList();
        logger.info(limit);
        logger.info("list of steps " + result);

        return result;

    }

**Comment by sasha802** [comment]
It works with my test as well.


    @Test
    void getByMultiplePropertiesTopClauseSuccess() {

        Map<String, Map<String, String>> entities = new HashMap<>();
        Map<String, String> propertiesOne = new HashMap<>();
        Map<String, String> propertiesTwo = new HashMap<>();

        propertiesOne.put("id", "1");
        propertiesTwo.put("level", "basic");

        entities.put("dance", propertiesOne);
        entities.put("", propertiesTwo);


        List<Step> step = genericDAO.getByMultiplePropertiesTopClause(entities, 3);

        assertEquals(3, step.size());

    }

**Comment by pawaitemadisoncollege** [comment]
That's look better! I like the user the limit there too.  Are you able to accomplish everything with the generic dao now?

**Comment by sasha802** [comment]
Yes, thank you.

**Comment by pawaitemadisoncollege** [comment]
Great! Congrats on taking your code to the next level!

**Comment by sasha802** [comment]
I am getting 53% of the line coverage and 77% for methods coverage. 
0% for servlets. Otherwise, all of my methods are covered except for hashCode()

**Comment by sasha802** [comment]
<img width="509" alt="screen shot 2018-10-07 at 1 18 06 pm" src="https://user-images.githubusercontent.com/35584625/46585207-792dfd00-ca33-11e8-9e83-3f539ebf2aeb.png">

**Comment by pawaitemadisoncollege** [comment]
Good!
