### ISSUE TITLE
Choreography Peer Review

### ISSUE THREAD

**Issue by kdkoberle** [sasha802/choreography_builder#4]
# Design/Code Review 1

### Reviewer: Keith Koberle

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|
|**Problem Statement**|1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person| The problem statement is very concise, but descriptive.  Perhaps it could be expanded on a little as to how the choreography can be chosen, or matched up to couples and their desired dance style, etc.  |
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens | All design documents are clear, and demonstrative of the point of each page. |
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>| The data model represents the data well, and project requirements are met. |
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverages. | Class code is very clean, concise, but also adaptive.  Very nice work.  Maybe controller code could be further streamlined with custom-tags? | 
  
Very nice work, the site seems almost done, and not having much room for constructive ideas.

**Comment by sasha802** [comment]
Thank you for your feedback Keith.
