### ISSUE TITLE
Week 9 Feedback

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [sasha802/choreography_builder#7]
Nice job implementing REST in a useful way in your application. 

- [ ] One thing to review is the REST naming standards. Think about the resource you are returning, which is STEPS, rather than STEPDATA: 
https://github.com/sasha802/choreography_builder/blob/f6413d92995be4dc3fb23ec0a7d57c61292d2bdb/src/main/java/services/StepProcessor.java#L12
- [ ] Does this actually produce JSON or is it just text? https://github.com/sasha802/choreography_builder/blob/f6413d92995be4dc3fb23ec0a7d57c61292d2bdb/src/main/java/services/StepProcessor.java#L16

**Comment by sasha802** [comment]
Thank you.
