### ISSUE TITLE
Instructor Feedback Week 15

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [sasha802/choreography_builder#9]
You've put in a lot of work here and I'm looking forward to seeing the final product!

- [x] developmentJournal.md - since this was not "kept up" throughout the project, it might be good to remove it, as it appears to be incomplete and prospective employers might wonder why it is not more complete.
- [x] Compare the entire entity where appropriate using .equals, rather than a single value on the entity: https://github.com/sasha802/choreography_builder/blob/4396ed08ed3dc2d1b8e9f6283bf4cc2e2c03eb89/src/test/java/dance/builder/persistence/UserDAOTest.java#L59
- [x] Verify all methods are javadoc'd. A few are missing, for example: https://github.com/sasha802/choreography_builder/blob/4396ed08ed3dc2d1b8e9f6283bf4cc2e2c03eb89/src/test/java/dance/builder/persistence/UserDAOTest.java#L73-L75
- [x] Is there a unit test to cover the Role db access/relationship.
- [x] Watch for redundancy. For example, this code block (or code that is very similar) is used in several places. How might you eliminate that redundancy? https://github.com/sasha802/choreography_builder/blob/570a323d8734100901ae882c1b05bccbde663aac/src/main/java/dance/builder/controller/SearchStep.java#L123-L130
- [x] What is the user experience when something goes wrong, i.e., the database is down? Custom error page/s can help with this.

**Comment by stasRevin** [comment]
Here is the user experience if database goes down:
![image](https://user-images.githubusercontent.com/32783730/49704784-172d7780-fbdd-11e8-99d7-eb5b7372e3eb.jpeg)

**Comment by sasha802** [comment]
<img width="1765" alt="404" src="https://user-images.githubusercontent.com/35584625/49845507-9dd48700-fd8c-11e8-88b4-b1401ef76fc0.png">

**Comment by sasha802** [comment]
<img width="1768" alt="500" src="https://user-images.githubusercontent.com/35584625/49845520-a5942b80-fd8c-11e8-8d26-f5b11bcd8c07.png">
